// <auto-generated />
using System;
using DesafioPicPay.Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DesafioPicPay.Infrastructure.Migrations
{
    [DbContext(typeof(DbContextConf))]
    [Migration("20240803005105_UpdateTableUsersAddCollunTypeUser")]
    partial class UpdateTableUsersAddCollunTypeUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DesafioPicPay.Core.Models.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal");

                    b.Property<string>("CostumerName")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("AccountId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("DesafioPicPay.Core.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("CpfCnpj")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<char>("TypeUser")
                        .HasColumnType("char(1)");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DesafioPicPay.Core.Models.Account", b =>
                {
                    b.HasOne("DesafioPicPay.Core.Models.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("DesafioPicPay.Core.Models.Account", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DesafioPicPay.Core.Models.User", b =>
                {
                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
